_target_: src.models.resnet50_module.Resnet50Module

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1
  weight_decay: 1e-4
  momentum: 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 30
  gamma: 0.1
  
net:
  _target_: torchvision.models.resnet50

# compile model for faster training with pytorch 2.0
compile: false
